name: dristi_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.7

flutter_native_splash:
  color: "#2899bd"
  image: images/app_icon.png


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/


